### ISSUE TITLE
csv. export not working

### ISSUE THREAD

**Issue by albuslondon** [berkon/wireless-microphone-analyzer#16]
Hi!
I just found your great Software and it works perfectly so far, except that it`s not possible to export a .csv File :( 
I`m running on Win10, RF Explorer Firmware is Up-to-Date... the export Window opens, i can give a Filename and hit Save (window closes normaly after that) but no File is genereated. 
Is it just me having this issue?
This would be the most important Part for me, to be able to import Scan Data to Shure WWB...
thanks

p.s.: I also tried the 3 last Versions!

**Comment by berkon** [comment]
Hi @albuslondon, I'm very glad to hear that you enjoy my little tool. That's indeed strange. I must admit that I'm not using the export function by myself, but I just tried with version 1.7.3 (latest) and it works fine. Please perform the following steps, so that we can find out more about what's going on:

- Start the tool
- Press <CTRL><SHIFT><ALT><i>
- A debug window will open. Make sure to be on "Console" tab
- Now do the export again and let me know if there are any error messages (if yes, pleas post them here)

Regards,
Bernd

**Comment by berkon** [comment]
Closing due to missing response.
