### ISSUE TITLE
Scan 2.4G and 5G wifi bands

### ISSUE THREAD

**Issue by JonnyTech** [berkon/wireless-microphone-analyzer#22]
I am not a microphone guy, and use the RF Explorer to scan for wifi congestion on the 2.4G and 5G bands. Is is possible to adapt this software to display those frequencies? Is it a case of writing a .json file with relevant details? If so do you have any documentation as there are many folders in the `frequency_data` folder so not sure which I should use and what the correct format is.

**Comment by berkon** [comment]
The tool is optimized for wireless microphones and thus has an FM channel width (frequency shift) which is typical for wireless microphones (+/-48kHz) and some other specific settings. WiFi channels have a much higher bandwidth. Of course this could be adapted in the software, but I don't think its worth the work, because the RF Explorer itself already has a very nice mode for scanning WiFi channels and showing the result graphically on its display. Just have look, maybe it already does what you need.
