### ISSUE TITLE
Contribution assistance if needed

### ISSUE THREAD

**Issue by matt-dale** [berkon/wireless-microphone-analyzer#44]
In the SoundBase (soundbase.app) Discord, your amazing app has been mentioned as a way to obtain a CSV from a tinySA in a Mac & Windows way. 

I noticed two things after forking this repo regarding the tinySA. 
1. When switching out of band for the tinySA BASIC, it doesn't switch to the "HIGH" or "LOW" mode. 
2. I've noticed through developing SoundBase Pro, with both tinySA BASIC and ULTRA, the total number of points is nearly limitless when using the "scanraw" command and you can obtain a much higher data capture density. We typically recommend 1500 points to obtain a very high resolution scan (no matter the start and stop frequency)

Do you have any ideas how I can contribute to this end? I don't want to change what you've done, and want to respect your processes.

**Comment by berkon** [comment]
Hi @matt-dale,

thanks a lot for your offer, your welcome!

1. You are absolutely right! That is because I initially started the project with the RF Explorer hardware. Recently I've added support for TinySA as well and there I admit that I concentrated on the Ultra model which does not have this switching. But it is good that you brought up this point. I will have look into that. If you already have a solution, feel free to create a pull request.
2. For both TinySA models I took the upper sweep point limits from the menus of the corresponding device, because I couldn't find that information in the technical data. Sure I can remove that limit. There is just one thing that makes me wonder if it will still deliver accurate data in that case. E.g. if you look at the minimum frequency, the doc states 100kHz (for both models). In the device you can set even lower frequencies (down to 0Hz). But in that case the the graph looks really strange. Exactly at 100kHz it starts to look useful. So maybe they have this official limitation, to ensure you're not getting wrong data. So maybe that's similar with the sweep points. I'll have a look.

Regards,
Bernd

**Comment by matt-dale** [comment]
Ok cool! I'll see if I can make a PR for the HI/LO switching.

Re: point #2, the documentation that I used was just for the scanraw command. The word "unlimited" had me suspicious, but in general it works quite well. 

> scanraw
> performs a scan of unlimited amount of points and send the data in binary form
> usage: scanraw {start(Hz)} {stop(Hz)} [points]

**Comment by matt-dale** [comment]
Ah, ok understood. 

That's where might we differ in the primary purpose of this app since there are two usages I see. 

1. Real-time sweep with max hold (where we would like to see intermittent peaks)
2. Exporting a survey of the RF environment to CSV to see which TV channels are active in the area for use in another tool (this is the angle I'm coming from)

For example, here's an sweep with 450 points.
<img width="1294" alt="Screenshot 2024-06-26 at 8 13 55 AM" src="https://github.com/berkon/wireless-microphone-analyzer/assets/1197303/ce5f4bb3-b584-4119-a0d8-29f406406ac9">

And here's one with 1500 points:
<img width="1300" alt="Screenshot 2024-06-26 at 8 13 43 AM" src="https://github.com/berkon/wireless-microphone-analyzer/assets/1197303/a32a84f4-253b-49b6-b783-b6388f3a27ea">


With the 1500 point one, I can be more confident that the data for each TV channel is accurate, including the spaces between adjacent channels.

**Comment by berkon** [comment]
I see. Then in the next release you should be able to set a higher sweep point number as required for your tool. I hope I can finish it within the next view days.

**Comment by berkon** [comment]
@matt-dale, I think I found a good automatic method of switching TinySA' LOW / HIGH mode. I just released V2.2.0

**Comment by matt-dale** [comment]
Wow! This is perfect!
Also, the removed restriction of sweep points is great (including the warning text)

Thank you so much for creating this

**Comment by berkon** [comment]
You're welcome! ;-)
